[build]
  command = "npm run build:client"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "http://172.105.43.82:8000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
